### ISSUE TITLE
大佬,请问汉字的笔画svg数据是如何生成的?

### ISSUE THREAD

**Issue by Jooyer** [MyMrXu/ChineseCharacterView#1]
大佬!
       你好,请问大佬,在生成某一个汉字笔画svg时,是使用啥方法,能否指点12, 我的QQ: 712952521, 微信: lanselyz520, 望大佬赐教!

**Comment by Alan-xzwzz** [comment]
> 大佬!
> 你好,请问大佬,在生成某一个汉字笔画svg时,是使用啥方法,能否指点12, 我的QQ: 712952521, 微信: lanselyz520, 望大佬赐教!

svg的数据从其他项目拿过来的,里面有保存对应的坐标点和笔画数据
你可以打开db数据库自己去查找
要增加汉字到数据库的话,我没多研究

**Comment by Jooyer** [comment]
多谢大佬！我继续研究哈！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;MyMrXu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 下午2:53
收件人:&nbsp;&quot;MyMrXu/ChineseCharacterView&quot;<ChineseCharacterView@noreply.github.com&gt;;
抄送:&nbsp;&quot;Jooyer&quot;<712952521@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyMrXu/ChineseCharacterView] 大佬,请问汉字的笔画svg数据是如何生成的? (#1)
